export const CONTACT_EMAIL = "info@mfdigitalstudio.com"
export const CONTACT_PHONE_DISPLAY = "+90 501 654 68 61"
export const CONTACT_PHONE_LINK = "tel:+905016546861"
export const WHATSAPP_URL = "https://wa.me/905016546861"
export const INSTAGRAM_URL = "https://www.instagram.com/mf.digitalstudio/"
export const BASE_URL = "https://www.mfdigitalstudio.com"

export const SITE_NAME = "MF Digital Studio"
export const DEFAULT_TITLE = "MF Digital Studio | Web Tasarım, E-Ticaret ve SEO Ajansı"
export const DEFAULT_DESCRIPTION = "MF Digital Studio; web tasarım, e-ticaret, SEO, sosyal medya yönetimi ve yönetim paneli çözümleriyle markanız için çalışan dijital sistemler kurar."
