export const projectsData = [
  {
    id: 1,
    slug: 'atolye-norte',
    title: 'Atölye Norte',
    category: 'Web Tasarım',
    type: 'Butik Kafe / Premium Marka',
    summary: 'Butik ve lüks bir kafe deneyimini dijitalde yalın, şık ve güven veren bir web sitesiyle yansıttık.',
    description: 'Butik ve lüks bir kafe deneyimini dijitalde yalın, şık ve güven veren bir web sitesiyle yansıttık.',
    services: ['Web Tasarım', 'UI/UX', 'Marka Deneyimi', 'Responsive'],
    year: '2024',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'Butik Kafe',
    projectType: 'Kurumsal Marka Sitesi',
    liveUrl: '#',
    tags: ['Web Tasarım', 'UI/UX', 'Marka Deneyimi'],
    mainImage: '/images/projects/norte-wallpaper.png',
    secondaryImage: '/images/projects/norte-inner.png',
    featured: true,
    sections: {
      ozet: 'Atölye Norte için dijital dünyada fiziksel mekanın sıcaklığını ve premium hissini yansıtan bir web deneyimi tasarladık. Amacımız, misafirlerin kahve kalitesini ve atmosferi siteye girdikleri an hissetmelerini sağlamaktı.',
      hedef: 'Mevcut hedef kitleyi genişletmek ve dijital kanallar üzerinden marka bilinirliğini artırırken, rezervasyon ve iletişim süreçlerini daha kurumsal bir yapıya kavuşturmak.',
      cozum: 'Yalın ve modern bir tasarım dili oluşturduk. Geniş tipografi kullanımı, soft renk paletleri ve yüksek kaliteli görsellerle marka kimliğini destekledik. Menü ve lokasyon bilgilerini kullanıcı odaklı bir mimariyle sunduk.',
      sonuc: 'Yeni web sitesi yayına alındıktan sonra mobil trafik %45 artış gösterdi. Kullanıcıların sitede kalma süresi uzarken, marka imajı premium segmente daha güçlü bir şekilde konumlandırıldı.'
    }
  },
  {
    id: 2,
    slug: 'imediaff',
    title: 'imediaff',
    category: 'Global Web Sitesi',
    type: 'Influencer Marketing Agency',
    summary: 'Influencer marketing alanında global ölçekte hizmet veren bir ajans için modern, net ve uluslararası algısı güçlü bir web deneyimi oluşturduk.',
    description: 'Influencer marketing alanında global ölçekte hizmet veren bir ajans için modern, net ve uluslararası algısı güçlü bir web deneyimi oluşturduk.',
    services: ['Web Geliştirme', 'Kurumsal Site', 'Global Marka', 'UI Design'],
    year: '2024',
    platform: 'Web',
    process: ['Strateji', 'UI Design', 'Frontend'],
    clientType: 'Influencer Marketing Agency',
    projectType: 'Global Kurumsal Web Sitesi',
    liveUrl: '#',
    tags: ['Web Geliştirme', 'Kurumsal Site', 'Global Marka'],
    mainImage: '/images/projects/imediaff-wallpaper.png',
    secondaryImage: '/images/projects/imediaff-inner.png',
    featured: true,
    sections: {
      ozet: 'Global pazarda influencer ve markaları bir araya getiren imediaff için güven veren, kurumsal yapıyı yansıtan uluslararası bir dijital yüz tasarladık.',
      hedef: 'Ajansın global arenadaki profesyonel duruşunu yansıtmak, dünya çapındaki markalar ve influencerlar için modern, anlaşılır ve güven verici bir iletişim noktası oluşturmak.',
      cozum: 'Koyu renklerin hakim olduğu, keskin ve modern bir kurumsal kimlik uyguladık. Başarı hikayelerini öne çıkaran asimetrik grid yapıları ve net tipografi kullandık.',
      sonuc: 'Yenilenen yüzüyle imediaff, uluslararası markalarla olan etkileşimini dijitalde %60 oranında artırdı. B2B iletişimde güçlü bir marka prestiji sağlandı.'
    }
  },
  {
    id: 3,
    slug: 'atelier',
    title: 'Atelier',
    category: 'Web Tasarım',
    type: 'Creative Studio',
    summary: 'Sanatsal ve modern bir yaklaşımla tasarlanan kreatif stüdyo web sitesi.',
    description: 'Sanatsal ve modern bir yaklaşımla tasarlanan kreatif stüdyo web sitesi.',
    services: ['Web Tasarım', 'UI/UX', 'Geliştirme'],
    year: '2024',
    platform: 'Web',
    process: ['Konsept', 'Tasarım', 'Geliştirme'],
    clientType: 'Kreatif Stüdyo',
    projectType: 'Portfolyo Sitesi',
    liveUrl: '#',
    tags: ['Kreatif', 'Tasarım', 'Portfolyo'],
    mainImage: '/images/projects/atelier-wallpaper.png',
    secondaryImage: '/images/projects/atelier-inner.png',
    featured: false,
    sections: {
      ozet: 'Atelier için sanatsal vizyonlarını yansıtan modern bir dijital deneyim kurguladık.',
      hedef: 'Projeleri ön plana çıkaran, dikkat dağıtmayan bir portfolyo oluşturmak.',
      cozum: 'Geniş boşluklar, minimalist bir yaklaşım ve zarif tipografi ile projeler sergilendi.',
      sonuc: 'Kullanıcı etkileşimi artarak potansiyel müşterilerde unutulmaz bir izlenim bırakıldı.'
    }
  },
  {
    id: 4,
    slug: 'coffee',
    title: 'Coffee',
    category: 'E-Ticaret',
    type: 'Kahve Markası',
    summary: 'Özel kahve çekirdekleri sunan bir marka için e-ticaret odaklı web sitesi tasarımı.',
    description: 'Özel kahve çekirdekleri sunan bir marka için e-ticaret odaklı web sitesi tasarımı.',
    services: ['E-Ticaret', 'UI/UX', 'Frontend'],
    year: '2024',
    platform: 'Web',
    process: ['Strateji', 'Arayüz', 'Geliştirme'],
    clientType: 'Kahve Markası',
    projectType: 'E-Ticaret Sitesi',
    liveUrl: '#',
    tags: ['E-Ticaret', 'UI/UX', 'Satış'],
    mainImage: '/images/projects/coffee-wallpaper.png',
    secondaryImage: '/images/projects/coffee-inner.png',
    featured: false,
    sections: {
      ozet: 'Coffee markasının ürün satışlarını artırmak amacıyla kullanıcı dostu bir e-ticaret altyapısı tasarlandı.',
      hedef: 'Satın alma sürecini basitleştirmek ve mobil deneyimi kusursuz hale getirmek.',
      cozum: 'Sade ve net bir ödeme adımı, kaliteli ürün görselleri ile desteklendi.',
      sonuc: 'Mobil üzerinden gelen sipariş oranlarında büyük bir artış yakalandı.'
    }
  },
  {
    id: 5,
    slug: 'forma',
    title: 'Forma',
    category: 'Web Tasarım',
    type: 'Kurumsal Marka',
    summary: 'Kurumsal yapıya sahip bir firma için modern ve profesyonel bir web varlığı.',
    description: 'Kurumsal yapıya sahip bir firma için modern ve profesyonel bir web varlığı.',
    services: ['Web Tasarım', 'Kurumsal Site', 'UI Design'],
    year: '2024',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'Kurumsal',
    projectType: 'Kurumsal Site',
    liveUrl: '#',
    tags: ['Kurumsal', 'Tasarım', 'UI'],
    mainImage: '/images/projects/forma-wallpaper.png',
    secondaryImage: '/images/projects/forma-mobile.png',
    featured: false,
    sections: {
      ozet: 'Forma için marka kimliğine uygun, profesyonel bir kurumsal site oluşturuldu.',
      hedef: 'Firmanın hizmetlerini ve başarılarını daha net bir şekilde sunmak.',
      cozum: 'Temiz bir tasarım dili ve kolay gezinilebilir menü mimarisi uygulandı.',
      sonuc: 'Müşteri dönüşüm oranları ve iletişim formu doldurma oranlarında artış sağlandı.'
    }
  },
  {
    id: 6,
    slug: 'lumiere',
    title: 'Lumiere',
    category: 'Web Tasarım',
    type: 'Premium Marka',
    summary: 'Premium bir algı yaratmak üzere tasarlanmış modern web arayüzü.',
    description: 'Premium bir algı yaratmak üzere tasarlanmış modern web arayüzü.',
    services: ['Web Tasarım', 'UI/UX', 'Marka Deneyimi'],
    year: '2024',
    platform: 'Web',
    process: ['Konsept', 'Tasarım', 'Geliştirme'],
    clientType: 'Premium',
    projectType: 'Marka Sitesi',
    liveUrl: '#',
    tags: ['Premium', 'Tasarım', 'UI/UX'],
    mainImage: '/images/projects/lumiere-wallpaper.png',
    secondaryImage: '/images/projects/lumiere-mobile.png',
    featured: false,
    sections: {
      ozet: 'Lumiere markası için zarif ve lüks hissettiren bir dijital deneyim tasarlandı.',
      hedef: 'Markanın üst segment algısını web sitesine yansıtmak.',
      cozum: 'Koyu temalar, şık animasyonlar ve yüksek çözünürlüklü görseller kullanıldı.',
      sonuc: 'Marka prestiji dijital ortamda başarıyla temsil edildi.'
    }
  },
  {
    id: 7,
    slug: 'nuans',
    title: 'Nuans',
    category: 'Web Tasarım',
    type: 'Kreatif Ajans',
    summary: 'Yenilikçi ve dinamik bir ajans için tasarlanmış modern web sitesi.',
    description: 'Yenilikçi ve dinamik bir ajans için tasarlanmış modern web sitesi.',
    services: ['Web Tasarım', 'UI/UX', 'Animasyon'],
    year: '2024',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Frontend'],
    clientType: 'Ajans',
    projectType: 'Kurumsal Site',
    liveUrl: '#',
    tags: ['Kreatif', 'Ajans', 'Tasarım'],
    mainImage: '/images/projects/nuans-wallpaper.png',
    secondaryImage: '/images/projects/nuans-mobile.png',
    featured: false,
    sections: {
      ozet: 'Nuans için ajansın dinamik yapısını yansıtan yaratıcı bir site kurgulandı.',
      hedef: 'Farklılaşan, modern ve etkileşimli bir deneyim sunmak.',
      cozum: 'Asimetrik düzenler ve akıcı geçiş animasyonları entegre edildi.',
      sonuc: 'Ziyaretçilerin sitede geçirdiği süre arttı ve marka algısı güçlendi.'
    }
  }
]
