export const projectsData = [
  {
    id: 1,
    slug: 'atolye-norte',
    title: 'Atölye Norte',
    category: 'Web Siteleri',
    type: 'Butik Kafe / Premium Marka',
    summary: 'Atölye Norte’nin butik ve rafine atmosferini dijitale taşıyan; menü, şube bilgileri ve marka deneyimini bütüncül bir akışta buluşturan bir web sitesi tasarladık.',
    description: 'Atölye Norte’nin butik ve rafine atmosferini dijitale taşıyan; menü, şube bilgileri ve marka deneyimini bütüncül bir akışta buluşturan bir web sitesi tasarladık.',
    services: ['Web Tasarım', 'UI/UX', 'Menü Sunumu', 'Şube Bilgileri', 'Marka Deneyimi'],
    year: '2026',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'Butik Kafe',
    projectType: 'Web Sitesi',
    liveUrl: 'https://atolye-norte.vercel.app/',
    tags: ['Web Tasarım', 'UI/UX', 'Menü Sunumu', 'Şube Bilgileri', 'Marka Deneyimi'],
    mainImage: '/images/projects/norte-wallpaper.png',
    secondaryImage: '/images/projects/norte-inner.png',
    featured: true,
    sections: {
      ozet: 'Atölye Norte için, markanın butik ve lüks kafe kimliğini dijitalde güçlü biçimde yansıtan bir web deneyimi tasarladık. Menü sunumu, iki şubeye ait bilgi akışı ve marka anlatısını tek bir yapıda bir araya getirerek daha bütünlüklü bir dijital vitrin oluşturduk.',
      hedef: 'Ziyaretçilerin Atölye Norte’nin atmosferini ilk anda hissedebilmesini; menüye, şube bilgilerine ve iletişim detaylarına zahmetsizce ulaşabilmesini sağlamak. Aynı zamanda markanın premium konumlanmasını dijitalde tutarlı biçimde yansıtmak.',
      cozum: 'Tasarım dilini sıcak görsel tonlar, rafine tipografi ve sade içerik akışı üzerine kur. İki şubeli yapıyı anlaşılır biçimde sun. Kullanıcıyı yormayan, marka algısı ve kullanılabilirliği dengeli biçimde taşıyan bir deneyim oluştur.',
      sonuc: 'Ortaya, Atölye Norte’nin karakterini dijitalde güçlü biçimde yansıtan, menü ve şube deneyimini akıcı hale getiren premium bir web sitesi çıktı. Marka artık ziyaretçilerine estetik ve işlevsel açıdan daha tutarlı bir dijital deneyim sunuyor.'
    }
  },
  {
    id: 2,
    slug: 'imediaff',
    title: 'imediaff',
    category: 'Global Web Sitesi',
    type: 'Influencer Marketing Agency',
    summary: 'Influencer marketing alanında global ölçekte hizmet veren bir ajans için modern, net ve uluslararası algısı güçlü bir web deneyimi oluşturduk.',
    description: 'Influencer marketing alanında global ölçekte hizmet veren bir ajans için modern, net ve uluslararası algısı güçlü bir web deneyimi oluşturduk.',
    services: ['Web Geliştirme', 'Kurumsal Site', 'Global Marka'],
    year: '2026',
    platform: 'Web',
    process: ['Strateji', 'UI Design', 'Frontend'],
    clientType: 'Influencer Marketing Agency',
    projectType: 'Global Web Sitesi',
    liveUrl: 'https://imediaff-global.vercel.app/',
    tags: ['Web Geliştirme', 'Kurumsal Site', 'Global Marka'],
    mainImage: '/images/projects/imediaff-wallpaper.png',
    secondaryImage: '/images/projects/imediaff-inner.png',
    featured: true,
    sections: {
      ozet: 'imediaff için, influencer marketing alanında global ölçekte hizmet veren bir ajansın dijitalde daha net, modern ve güven veren bir marka algısı oluşturmasını hedefleyen kurumsal bir web deneyimi geliştirdik.',
      hedef: 'Markanın hizmet yapısını, global çalışma modelini ve ajans uzmanlığını ziyaretçilere hızlı ve anlaşılır şekilde aktarmak. Potansiyel marka iş birlikleri ve içerik üreticileri için güven veren, sade ve profesyonel bir dijital vitrin oluşturmak.',
      cozum: 'Tasarım dilini uluslararası ajans algısına uygun şekilde sade, net ve modern bir yapı üzerine kur. Hizmetleri, değer önerisini ve iletişim akışını kullanıcıyı yormadan ilerleyen bir deneyim içinde sun.',
      sonuc: 'Ortaya, imediaff’in global influencer marketing konumunu dijitalde daha güçlü yansıtan, kurumsal güveni artıran ve kullanıcıyı iletişim aksiyonuna yönlendiren modern bir web sitesi çıktı.'
    }
  },
  {
    id: 3,
    slug: 'lumiere-estetik',
    title: 'LUMIÈRE',
    category: 'Web Siteleri',
    type: 'Estetik Klinik / Premium Sağlık Deneyimi',
    summary: 'Lumière Estetik için; premium klinik atmosferini, uzman kadroyu ve kişiye özel bakım protokollerini rafine bir dijital deneyimde buluşturan bir web sitesi tasarladık.',
    description: 'Lumière Estetik için; premium klinik atmosferini, uzman kadroyu ve kişiye özel bakım protokollerini rafine bir dijital deneyimde buluşturan bir web sitesi tasarladık.',
    services: ['Web Tasarım', 'Klinik Web Sitesi', 'UI/UX', 'Hizmet Sunumu', 'Randevu Akışı'],
    year: '2026',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'Estetik Klinik',
    projectType: 'Web Sitesi',
    liveUrl: 'https://lumiere-estetik-inky.vercel.app/',
    tags: ['Web Tasarım', 'Klinik Web Sitesi', 'UI/UX', 'Hizmet Sunumu', 'Randevu Akışı'],
    mainImage: '/images/projects/lumiere-wallpaper.png',
    secondaryImage: '/images/projects/lumiere-mobile.png',
    featured: false,
    sections: {
      ozet: 'Lumière Estetik için, kliniğin premium görünümünü ve güven veren uzmanlık yaklaşımını dijitalde güçlü biçimde yansıtan bir web deneyimi tasarladık. Hizmetler, klinik yaklaşımı, uzman kadro ve iletişim akışını tek bir bütünlük içinde bir araya getirerek daha rafine bir dijital vitrin oluşturduk.',
      hedef: 'Ziyaretçilerin Lumière’in doğal güzellik anlayışını ilk temas anında hissedebilmesini; hizmetleri, teknolojik altyapıyı ve randevu adımlarını zahmetsizce keşfedebilmesini sağlamak. Aynı zamanda premium klinik algısını destekleyen güven veren ve dönüşüm odaklı bir yapı kurmak.',
      cozum: 'Tasarım dilini yumuşak görsel geçişler, seçkin tipografi ve sakin bir içerik akışı üzerine kur. Lazer epilasyon, medikal cilt bakımı ve bölgesel incelme gibi hizmetleri öne çıkar. Uzmanlık ve teknoloji vurgusunu randevu/iletişim noktalarıyla dengeli biçimde konumlandır.',
      sonuc: 'Ortaya, Lumière Estetik’in marka algısını dijitalde güçlendiren ve ziyaretçiyi bilgi alma ile randevu aksiyonuna akıcı biçimde taşıyan bütüncül bir web deneyimi çıktı. Klinik artık premium hizmet anlayışını ve güven veren yapısını dijitalde daha tutarlı biçimde sunuyor.'
    }
  },
  {
    id: 4,
    slug: 'atelier-29',
    title: 'ATELIER 29',
    category: 'Web Siteleri',
    type: 'Restoran / Premium Deneyim',
    summary: 'Atelier 29’un seçkin atmosferini dijitale taşıyan; menü, rezervasyon ve marka deneyimini rafine bir akışta buluşturan bir web sitesi tasarladık.',
    description: 'Atelier 29’un seçkin atmosferini dijitale taşıyan; menü, rezervasyon ve marka deneyimini rafine bir akışta buluşturan bir web sitesi tasarladık.',
    services: ['Web Tasarım', 'Restoran Web Sitesi', 'Menü', 'Rezervasyon', 'Marka Deneyimi'],
    year: '2026',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'Restoran',
    projectType: 'Web Sitesi',
    liveUrl: 'https://mf-fine-dining.vercel.app/',
    tags: ['Web Tasarım', 'Restoran Web Sitesi', 'Menü', 'Rezervasyon', 'Marka Deneyimi'],
    mainImage: '/images/projects/atelier-wallpaper.png',
    secondaryImage: '/images/projects/atelier-inner.png',
    featured: false,
    sections: {
      ozet: 'Atelier 29 için, restoranın lüks ve karakter sahibi atmosferini dijitalde güçlü biçimde yansıtan bir web deneyimi tasarladık. Menü sunumu, rezervasyon erişimi ve marka anlatısını tek bir bütünlük içinde ele aldık.',
      hedef: 'Ziyaretçilerin Atelier 29’un atmosferini ilk temas anında hissedebilmesini ve menü ile rezervasyon adımlarına zahmetsizce ulaşabilmesini sağlamak. Aynı zamanda markanın seçkin konumlanmasını dijitalde daha güçlü ve tutarlı biçimde yansıtmak.',
      cozum: 'Tasarım dilini rafine tipografi, güçlü görsel vurgu ve sade içerik akışı üzerine kur. Kullanıcıyı yormayan bir yapı oluştur. Restoranın premium algısını destekleyen, estetik ve işlevsel dengesi yüksek bir deneyim tasarla.',
      sonuc: 'Ortaya, Atelier 29’un marka algısını güçlendiren ve kullanıcıyı menü ile rezervasyon deneyimine akıcı biçimde yönlendiren bütüncül bir dijital vitrin çıktı. Restoran artık dijitalde de fiziksel deneyimiyle uyumlu, seçkin ve güven veren bir görünüm sunuyor.'
    }
  },
  {
    id: 5,
    slug: 'koro-coffee-web',
    title: 'KORO COFFEE',
    category: 'Web Siteleri',
    type: 'Coffee Shop / Menü ve Rezervasyon Deneyimi',
    summary: 'Koro Coffee’nin sıcak ve karakter sahibi atmosferini dijitale taşıyan; menü, rezervasyon ve marka deneyimini tek akışta buluşturan bir web sitesi tasarladık.',
    description: 'Koro Coffee’nin sıcak ve karakter sahibi atmosferini dijitale taşıyan; menü, rezervasyon ve marka deneyimini tek akışta buluşturan bir web sitesi tasarladık.',
    services: ['Web Tasarım', 'Coffee Shop', 'Menü', 'Rezervasyon', 'Marka Sunumu'],
    year: '2026',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'Coffee Shop',
    projectType: 'Web Sitesi',
    liveUrl: 'https://mf-cafe-landing.vercel.app/',
    tags: ['Web Tasarım', 'Coffee Shop', 'Menü', 'Rezervasyon', 'Marka Sunumu'],
    mainImage: '/images/projects/coffee-wallpaper.png',
    secondaryImage: '/images/projects/coffee-inner.png',
    featured: false,
    sections: {
      ozet: 'Koro Coffee için, markanın atmosferini dijitalde güçlü biçimde yansıtan bütüncül bir web deneyimi tasarladık. Menü erişimi, rezervasyon ve marka sunumunu tek bir akış içinde bir araya getirerek kullanıcı için daha akıcı bir deneyim oluşturduk.',
      hedef: 'Ziyaretçilerin Koro Coffee’nin dünyasını ilk temas anında hissedebilmesini; menüye kolayca ulaşmasını ve rezervasyon sürecini minimum adımla tamamlayabilmesini sağlamak. Mobil kullanımda hızlı, anlaşılır ve güven veren bir yapı oluşturmak.',
      cozum: 'Tasarım dilini güçlü tipografi, sıcak görsel tonlar ve sade bir içerik akışı üzerine kur. Markanın karakterini öne çıkar. Etkileşim noktalarını sadeleştirerek deneyimi hem estetik hem de işlevsel açıdan dengeli hale getir.',
      sonuc: 'Ortaya, Koro Coffee’nin dijital görünümünü güçlendiren ve kullanıcıyı doğru aksiyonlara akıcı biçimde yönlendiren bir deneyim çıktı. Menü inceleme, rezervasyon ve marka algısı artık tek bir yapıda daha güçlü ve tutarlı şekilde sunuluyor.'
    }
  },
  {
    id: 6,
    slug: 'forma',
    title: 'FORMA',
    category: 'Web Siteleri',
    type: 'Mobilya / Koleksiyon Vitrini',
    summary: 'FORMA için; dengeli formlar ve doğal dokularla kurduğu marka dilini dijitale taşıyan, koleksiyon keşfini ve ürün hikayelerini akıcı bir akışta birleştiren premium bir web sitesi tasarladık.',
    description: 'FORMA için; dengeli formlar ve doğal dokularla kurduğu marka dilini dijitale taşıyan, koleksiyon keşfini ve ürün hikayelerini akıcı bir akışta birleştiren premium bir web sitesi tasarladık.',
    services: ['Web Tasarım', 'Ürün Vitrini', 'Koleksiyon', 'Mobilya', 'Premium Marka'],
    year: '2026',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'Mobilya',
    projectType: 'Web Sitesi',
    liveUrl: 'https://forma-mobilya.vercel.app/',
    tags: ['Web Tasarım', 'Ürün Vitrini', 'Koleksiyon', 'Mobilya', 'Premium Marka'],
    mainImage: '/images/projects/forma-wallpaper.png',
    secondaryImage: '/images/projects/forma-mobile.png',
    featured: false,
    sections: {
      ozet: 'FORMA için, markanın denge, malzeme ve tasarım odağını dijitalde güçlü biçimde yansıtan bir vitrin deneyimi tasarladık. Öne çıkan parçalar, mekâna göre seçimler ve koleksiyon akışını tek bir bütünlükte kurgulayarak ürün keşfini daha sezgisel hale getirdik.',
      hedef: 'Ziyaretçilerin FORMA’nın sakin ve karakterli marka tonunu ilk temas anında hissetmesini; ürünlere, kategorilere ve marka hikayesine zahmetsizce ulaşabilmesini sağlamak. Ürün inceleme ve iletişim adımlarını görünür kılarak dönüşüm odaklı, güven veren bir deneyim oluşturmak.',
      cozum: 'Tasarım dilini geniş nefes alan boşluklar, güçlü görsel çerçeveler ve okunaklı tipografik hiyerarşi üzerine kur. Koleksiyon yapısını oturma, yemek, yatak ve çalışma alanı gibi kullanım senaryoları etrafında sadeleştir. Mobilde de akıcı bir keşif deneyimi sun.',
      sonuc: 'Ortaya, FORMA’nın premium ürün algısını dijitalde güçlendiren ve ziyaretçiyi ürün keşfinden aksiyona akıcı biçimde taşıyan bütüncül bir web deneyimi çıktı. Marka artık koleksiyonlarını daha tutarlı bir anlatıyla sunarken, kullanıcılar ihtiyaç duydukları ürünlere daha hızlı erişebiliyor.'
    }
  },
  {
    id: 7,
    slug: 'nuans',
    title: 'NUANS',
    category: 'Web Siteleri',
    type: 'İç Mimari / Özel Mobilya / Proje Vitrini',
    summary: 'NUANS için; iç mimari uzmanlığını, özel mobilya yaklaşımını ve proje vitrini akışını tek bir premium anlatıda birleştiren etkileyici bir web deneyimi tasarladık.',
    description: 'NUANS için; iç mimari uzmanlığını, özel mobilya yaklaşımını ve proje vitrini akışını tek bir premium anlatıda birleştiren etkileyici bir web deneyimi tasarladık.',
    services: ['Web Tasarım', 'İç Mimari', 'Özel Mobilya', 'Proje Vitrini', 'Premium Deneyim'],
    year: '2026',
    platform: 'Web',
    process: ['Strateji', 'Tasarım', 'Geliştirme'],
    clientType: 'İç Mimari',
    projectType: 'Web Sitesi',
    liveUrl: 'https://nuans-mimarlik.vercel.app/',
    tags: ['Web Tasarım', 'İç Mimari', 'Özel Mobilya', 'Proje Vitrini', 'Premium Deneyim'],
    mainImage: '/images/projects/nuans-wallpaper.png',
    secondaryImage: '/images/projects/nuans-mobile.png',
    featured: false,
    sections: {
      ozet: 'NUANS için, “Mekanları tasarlamıyoruz, deneyimler yaratıyoruz” yaklaşımını dijitalde hissettiren güçlü bir marka deneyimi tasarladık. Seçilmiş çalışmalar, hizmet modülleri ve iletişim akışını bütüncül bir yapıda birleştirerek hem ilham veren hem de aksiyona yönlendiren bir vitrin oluşturduk.',
      hedef: 'Ziyaretçilerin NUANS’ın iç mimari, özel mobilya, 3D görselleştirme ve anahtar teslim hizmetlerini ilk bakışta net biçimde kavrayabilmesini sağlamak. Aynı zamanda proje portföyünü görünür kılarak güven algısını güçlendiren ve iletişime geçişi hızlandıran bir yapı kurmak.',
      cozum: 'Tasarım kurgusunu hikaye anlatımı güçlü hero alanı, servis odaklı içerik blokları ve referans projelerle desteklenen katmanlı bir akış üzerine inşa et. Minimal görsel dil ve net bilgi mimarisiyle kullanıcıyı keşiften proje detaylarına, oradan da iletişim adımına doğal bir ritimde taşı.',
      sonuc: 'Ortaya, NUANS’ın premium konumunu dijitalde daha güçlü yansıtan ve markanın uzmanlık alanlarını anlaşılır şekilde görünür kılan bütüncül bir web deneyimi çıktı. Marka artık portföyünü ve hizmetlerini daha etkili sunarken, potansiyel müşteriler karar ve iletişim aşamasına daha hızlı ilerleyebiliyor.'
    }
  }
]
